# Generated by Django 5.2.3 on 2025-06-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_todomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoModel',
        ),
    ]
